debug: true
otp:
  key: WXaWKWrYvRDwducJ

ui:
  host: 127.0.0.1
  port: 9001
  secret: 9hucWbcL4mSXXoqa

agent:
  port: 9002
  secret: GUFCwkPNPdrzi4pv

pg:
  host: localhost
  db: scepter
  user: scepter
  password: scepter
